apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-placement-rule-sanctuary
  namespace: umbrella-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values: 
          - sanctuary
