apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: fleet-wide
  namespace: umbrella-gitops
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: manifests/acm/all
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: umbrella-gitops/umbrella-gitops
  placement:
    placementRef:
      name: openshift-all-placement-rule
      kind: PlacementRule
