apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-all-placement-rule
  namespace: umbrella-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values: 
          - OpenShift
