apiVersion: v2
name: advanced-cluster-management
description: Advanced Cluster Management
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
