---
acm:
  multiclusterhub:
    name: umbrella-hub
    availabilityConfig: High
    imagePullSecret: redhat-pull-secret
  targetNamespace: open-cluster-management

observability:
  deploy: true
  thanos:
    aws:
      bucketName: umbrella-observability-bucket
      credentialRequestName: umbrella-s3-credentials
      credentialRequestNamespace: umbrella
  setupJob:
    annotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
    gitRepository: https://github.com/nasx/phoenix.git
    gitBranch: main
    namespace: umbrella
    serviceAccount: ansible-runner-sa
  targetNamespace: open-cluster-management-observability
