---
acm:
  multiclusterhub:
    name: umbrella-hub
    availabilityConfig: High
    imagePullSecret: redhat-pull-secret
  pullSecretJob:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
    serviceAccount: ansible-runner-sa
    imagePullPolicy: Always
    name: acm-pull-secret-job
  targetNamespace: open-cluster-management

observability:
  deploy: true
  name: umbrella-observability
  thanos:
    aws:
      bucketName: umbrella-observability-bucket
      credentialRequestName: umbrella-s3-credentials
      credentialRequestNamespace: umbrella
  setupJob:
    annotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
    gitRepository: https://github.com/nasx/phoenix.git
    gitBranch: main
    namespace: umbrella
    serviceAccount: ansible-runner-sa
  storageClass: gp3-csi
  targetNamespace: open-cluster-management-observability
