apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.ansible_runner.serviceAccount }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
