apiVersion: v1
kind: Pod
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: ansible
  namespace: {{ template "common.names.namespace" $ }}
spec:
  containers:
    - name: ansible
      image: image-registry.openshift-image-registry.svc:5000/ansible-runner/ansible-runner:latest
      command:
        - /bin/bash
        - -c
        - |
          sleep infinity
  serviceAccountName: {{ $.Values.ansible_runner.serviceAccount }}
