
{{- if and $.Values.observability.deploy (has $.Values.observability.thanos.aws) -}}
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  name: {{ $.Values.observability.thanos.aws.credentialRequestName }}
  namespace: {{ $.Values.observability.thanos.aws.credentialRequestNamespace }}
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - s3:*
      effect: Allow
      resource: '*'
  secretRef:
    name: {{ $.Values.observability.thanos.aws.credentialRequestName }}
    namespace: {{ $.Values.observability.thanos.aws.credentialRequestNamespace }}
{{- end -}}
