apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.acm.pullSecretJob.name }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $.Values.acm.pullSecretJob.annotations | nindent 4}}
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - |
              export CLUSTER_PULL_SECRET=$(oc get secret pull-secret -n openshift-config -ogo-template='{{ index .data ".dockerconfigjson" | base64decode }}')
              echo -n $PULL_SECRET_DATA | \
                kubectl create secret generic {{ $.Values.acm.multiclusterhub.imagePullSecret }} \
                -n {{ $.Values.acm.targetNamespace }} \
                --from-file=.dockerconfigjson=/dev/stdin
          imagePullPolicy: {{ $.Values.acm.pullSecretJob.imagePullPolicy }}
          name: {{ $.Values.acm.pullSecretJob.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.acm.pullSecretJob.serviceAccount }}
      serviceAccountName: {{ $.Values.acm.pullSecretJob.serviceAccount }}
      terminationGracePeriodSeconds: 30
