apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.acm.pullSecretJob.name }}
  namespace: {{ $.Values.acm.pullSecretJob.namespace }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $.Values.acm.pullSecretJob.annotations | nindent 4}}
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - |
              export CLUSTER_PULL_SECRET=$(oc get secret pull-secret -n openshift-config -ogo-template='{{ index .data ".dockerconfigjson" }}')
              cat <<EOF | oc apply -f -
              apiVersion: v1
              data:
                .dockerconfigjson: $CLUSTER_PULL_SECRET
              kind: Secret
              metadata:
                name: {{ $.Values.acm.multiclusterhub.imagePullSecret }}
                namespace: {{ $.Values.acm.targetNamespace }}
              type: Opaque
              EOF
          imagePullPolicy: {{ $.Values.acm.pullSecretJob.imagePullPolicy }}
          name: {{ $.Values.acm.pullSecretJob.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.acm.pullSecretJob.serviceAccount }}
      serviceAccountName: {{ $.Values.acm.pullSecretJob.serviceAccount }}
      terminationGracePeriodSeconds: 30
