apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: openshift-mini-console
    path: route-patch.yaml

resources:
  - ../buildconfig
